export const landingContent = {
  ar: {
    hero: {
      line1: "مستقبل أبنائكم",
      line2: "يبدأ بخطوة ثابتة مع مَجْد",
      subtitle1: "دروس إلكترونية بالمنهج الإماراتي مع معلمين متخصصين يرعون أبناءكم ويوصلونهم إلى التفوق.",
      subtitle2: "",
      cta: "احجز حصة مجانية",
      badge1: "المنهج الإماراتي",
      badge1sub: "وزارة التربية والتعليم",
      badge2: "اللغة العربية",
      badge2sub: "والتربية الإسلامية",
      badge3: "الصف 1 - 12",
      badge3sub: "جميع المراحل",
    },
    interests: {
      heading: "من الروضة إلى الثاني عشر، أبناؤكم في أيدٍ",
      headingHighlight: "أمينة",
      cards: [
        { age: "سن 4-5", title: "مرحلة الروضة", description: "نُرسّخ أساساً تعليمياً ممتعاً من خلال الألعاب والأناشيد، لأن حبّ التعلم يبدأ من أول يوم.", link: "اعرف أكثر" },
        { age: "الصف 1-5", title: "المرحلة الابتدائية", description: "نبني أساساً متيناً في القراءة والكتابة والتعبير بأسلوب ممتع يُحبّب الطفلَ في التعلم منذ البداية.", link: "اعرف أكثر" },
        { age: "الصف 6-9", title: "المرحلة المتوسطة", description: "نُطوّر مهارات التفكير التحليلي والفهم العميق مع التركيز على اللغة العربية والتربية الإسلامية بالمنهج الإماراتي.", link: "اعرف أكثر" },
        { age: "الصف 10-12", title: "المرحلة الثانوية", description: "نرتقي بمستوى الطالب في اللغة العربية والتربية الإسلامية بمتابعة مكثفة ومراجعات شاملة.", link: "اعرف أكثر" },
      ],
      ctaBadge: "لغير الناطقين بالعربية · جميع الأعمار",
      ctaTitle: "دورة اللغة العربية",
      ctaDesc: "نُعلّم العربية من الصفر بأسلوب تفاعلي ممتع — قراءةً وكتابةً ومحادثةً، لأي عمر ودون ارتباط بمنهج محدد.",
      ctaButton: "سجّل الآن",
    },
    stats: {
      line1pre: "الخبرة أكثر من",
      line1num: "7",
      line1post: "سنوات في تدريس الناطقين وغير الناطقين باللغة العربية",
      line2num: "+200",
      line2post: "طالب",
      line3num: "+10",
      line3post: "معلم متخصص",
    },
    paths: {
      title: "فلسفة واحدة ومسارات\nمتعددة لكل مرحلة",
      items: [
        { age: "الصف 1-5", description: "يتعلم الأطفال من خلال اللعب والتجارب العملية. بمرافقة معلمهم، يستكشفون أشياء جديدة في بيئة آمنة تشجعهم على طرح الأسئلة.", tags: ["حصص قصيرة", "تعلّم ممتع", "تنمية الفضول"] },
        { age: "الصف 6-9", description: "يشرع الطلاب في بناء مهارات التفكير التحليلي والعمل على مشاريع حقيقية، مع تطوير قدراتهم في حل المشكلات والتفكير المنطقي.", tags: ["تفكير تحليلي", "مشاريع حقيقية", "متابعة مستمرة"] },
        { age: "الصف 10-12", description: "نرتقي بمستوى الطالب في اللغة العربية والتربية الإسلامية بمراجعات مكثفة وخطط دراسية مخصصة تتناسب مع مستواه وأهدافه.", tags: ["مهارات متقدمة", "خطة مخصصة", "مراجعات مكثفة"] },
      ],
      link: "اكتشف الباقات ←",
    },
    trial: {
      heading1: "ابدأ بـ",
      headingHighlight: "حصة تجريبية مجانية",
      heading2: "وتعرّف على أسلوبنا",
      steps: [
        { title: "تعرّف على المعلم", description: "تبدأ الحصة بالتعرف على ابنك — ما يحب، ما يلهمه، وأسلوبه في التعلم. كثير من الأطفال يشعرون بالخجل في البداية، لذا نركز على بناء الثقة وخلق أجواء هادئة وداعمة." },
        { title: "اكتشف المسار الملائم", description: "نوصي بأفضل خطة تعليمية بناءً على مستوى ابنك وعمره واحتياجاته، ونختار المواد والمعلم الأنسب له." },
        { title: "احصل على توصيات واضحة", description: "يُشارك المعلم ملاحظاته بصراحة: مستوى ابنك، أفضل نقطة انطلاق، والمحاور التي تستوجب التركيز. نُصمّم خطة التعلم وفق اهتماماته وأهدافه." },
      ],
      stepLabel: "الخطوة",
      cta: "جرّب الآن",
    },
    premiumHero: {
      title: "باقات مَجْد.. لأنهم يستحقون التميز",
      desc1: "استثمر في راحة أبنائك وتفوقهم مع باقات صُمّمت لتحتضنهم وتفهم أسلوبهم.",
      desc2: "منهج إماراتي متكامل بمتابعة تُحبّبهم في الدراسة، حتى يبلغوا",
      desc2highlight: "المَجْد",
      desc3: "وهم مرتاحون ومستمتعون.",
      cta: "اكتشف باقاتنا",
    },
    packages: {
      subtitle: "منهج إماراتي متكامل من الصف الأول حتى الثاني عشر",
      title: "اختر الباقة المناسبة",
      titleHighlight: "لأبنائك",
      cta: "احجز حصتك المجانية",
      items: [
        { title: "الباقة الشاملة", description: "المادتان معاً بسعر أفضل", price: "1600", period: "درهم / شهرياً", features: ["اللغة العربية + التربية الإسلامية", "10 حصص شهرياً مع معلمين متخصصين", "متابعة مستمرة لولي الأمر عبر واتساب", "حصص مراجعة قبل الامتحانات"] },
        { title: "الباقة الأساسية", description: "مادة واحدة بمتابعة مستمرة للعرب", price: "1000", period: "درهم / شهرياً", features: ["مادة واحدة (اللغة العربية أو التربية الإسلامية)", "6 حصص شهرياً مع معلم متخصص", "حصة تجريبية مجانية أولى", "تقرير شهري لولي الأمر"] },
      ],
    },
    guarantees: {
      title: "وعد مَجْد لأبنائكم",
      description: "ثقتكم بنا أمانة. نضمن لكم تجربة تعليمية مريحة ونسعى دائماً لتقديم الأفضل.",
      cardTitle: "ضماناتنا لكم",
      items: ["معلم بديل عند الحاجة", "حصة تعويضية عند الغياب", "جودة مضمونة", "دعم مستمر 7 أيام", "بيئة آمنة ومحترمة"],
      cta: "احجز حصة مجانية",
    },
    faq: {
      title: "الأسئلة الشائعة",
      subtitle: "إجابات عن أكثر الأسئلة التي تردنا من أولياء الأمور",
      items: [
        { question: "هل يمكن تغيير المعلم أو الجدول الزمني؟", answer: "بالتأكيد! راحة الطالب أولويتنا. تواصل معنا عبر واتساب أو البريد الإلكتروني وسنرتب لك التغيير في أقرب وقت ممكن دون أي تكلفة إضافية." },
        { question: "هل تعمل الحصص على الهاتف أو الجهاز اللوحي؟", answer: "نعم! تعمل الحصص على أي جهاز — حاسوب محمول، جهاز لوحي، أو هاتف ذكي. غير أننا نوصي بالحاسوب المحمول أو الجهاز اللوحي للحصول على تجربة أفضل." },
        { question: "كيف أتابع مستوى ابني؟", answer: "نُرسل إليك تقارير دورية عبر واتساب بعد كل حصة، إضافةً إلى تقرير شامل في نهاية كل شهر يتضمن تقييم المعلم وتوصياته." },
        { question: "هل ثمة حصة تجريبية مجانية؟", answer: "نعم! نوفر حصة تجريبية مجانية لتتعرف بنفسك على جودة التدريس وأسلوبنا قبل الالتزام بأي باقة." },
        { question: "كيف أتحقق من مصداقيتكم؟", answer: "نحن مسجّلون رسمياً ونعمل منذ أكثر من 3 سنوات مع مئات الأسر في الإمارات. يمكنك الاطلاع على آراء أولياء الأمور أو التواصل معنا مباشرةً." },
      ],
      ctaText: "لم تجد إجابتك؟ تواصل معنا",
    },
    testimonials: {
      subtitle: "آراء أولياء الأمور",
      title: "ثقتهم بنا",
      titleHighlight: "تحفّزنا",
      cta: "انضم إلى عائلة مَجْد",
      items: [
        { name: "أم عبدالله", grade: "الصف الرابع", subject: "اللغة العربية", text: "كان عبدالله يكره حصة اللغة العربية، غير أنه بعد انضمامه إلى مَجْد بات يطلب مني بنفسه حضور الحصة. أسلوب المعلمة رائع حقاً." },
        { name: "أم شمّا", grade: "الصف السابع", subject: "التربية الإسلامية", text: "كانت شمّا تعاني مع الحفظ، لكن المعلمة علّمتها أن تفهم المعنى أولاً ثم تحفظ. ارتفعت درجاتها من 70 إلى 95." },
        { name: "أم راشد", grade: "الصف العاشر", subject: "اللغة العربية", text: "حصل راشد على 98 في امتحان اللغة العربية النهائي. كان المعلم يتابعه يومياً ويراجع معه كل شيء. لم أكن أتوقع هذه النتيجة صراحةً." },
        { name: "أبو حمدان", grade: "الصف الثاني", subject: "اللغة العربية", text: "حمدان في السابعة من عمره وبات يقرأ بمفرده. الحصص قصيرة ومركّزة ولا يشعر بالملل منها. كان هذا أفضل قرار اتخذناه." },
        { name: "أم مريم", grade: "الصف التاسع", subject: "التربية الإسلامية", text: "كانت مريم تخشى الامتحانات، إلا أن المعلمة بنت لديها الثقة بالنفس فصارت تدخل الامتحان بكل اطمئنان. حصلت على العلامة الكاملة في الفصل الثاني." },
      ],
    },
    footer: {
      cta: "حصة مجانية",
      col1Title: "الأكاديمية",
      col1Links: ["عن مَجْد", "أسلوبنا", "المعلمون", "انضم معلماً", "الأسئلة الشائعة", "تواصل معنا"],
      col2Title: "المواد الدراسية",
      col2Links: ["اللغة العربية", "التربية الإسلامية", "العربية لغير الناطقين"],
      col3Title: "تواصل معنا",
      col3Desc: "تابع آخر العروض والأخبار التعليمية",
      col3Placeholder: "البريد الإلكتروني",
      col3Button: "اشترك",
      col3Address: "أكاديمية مَجْد للتعليم الإلكتروني\nالإمارات العربية المتحدة",
      copyright: "© مَجْد، 2026",
      privacy: "سياسة الخصوصية",
      terms: "شروط الاستخدام",
    },
    whyMajd: {
      title1: "لماذا ",
      title2: "مَجد؟",
      footer: "تابعوا تقدّم أبنائكم واطلعوا على مسارهم التعليمي، واحصلوا على ملاحظات المعلم بعد كل حصة.",
      features: [
        { title: "منهج إماراتي معتمد", desc: "نُدرّس وفق المنهج المعتمد من وزارة التربية والتعليم؛ وهو مطابق لما يدرسه الطالب في المدرسة، ولكن بأسلوب أكثر تفاعلية وفاعلية." },
        { title: "حصص إلكترونية تفاعلية", desc: "حصص فردية مع معلمين متخصصين يتابعون أبناءكم خطوة بخطوة لضمان استيعابهم التام." },
        { title: "معلمون خبراء في تخصصاتهم", desc: "فريقنا مؤهل ومتخصص في المنهج الإماراتي، ويتقن إيصال المعلومات بكفاءة عالية." },
        { title: "متابعة مستمرة لأولياء الأمور", desc: "تقارير دورية وتواصل مباشر، لتبقوا على دراية تامة بتطور مستوى أبنائكم." },
      ]
    },
    subjectsSection: {
      title1: "المواد ",
      title2: "التي ندرّسها",
      items: [
        { name: "اللغة العربية", desc: "نبني مهارات القراءة والكتابة والتعبير بأسلوب ممتع يُحبّب الطالبَ باللغة ويُعزز ثقته بنفسه.", cta: "احجز حصة مجانية" },
        { name: "التربية الإسلامية", desc: "نُرسّخ القيم والمفاهيم الإسلامية بطريقة قريبة من الطالب تربط الدين بحياته اليومية.", cta: "احجز حصة مجانية" },
      ]
    }
  },
  en: {
    hero: {
      line1: "Your kids' future",
      line2: "starts with a solid step with Majd",
      subtitle1: "Online classes following the UAE curriculum with specialized teachers who nurture your children and guide them to excel.",
      subtitle2: "",
      cta: "Book a Free Class",
      badge1: "UAE Curriculum",
      badge1sub: "Ministry of Education",
      badge2: "Arabic",
      badge2sub: "& Islamic Education",
      badge3: "Grades 1 - 12",
      badge3sub: "All Levels",
    },
    interests: {
      heading: "From Kindergarten to Grade 12, your kids are in",
      headingHighlight: "safe hands",
      cards: [
        { age: "Ages 4-5", title: "Kindergarten Stage", description: "We build a joyful learning foundation through play and songs — so they love learning from day one.", link: "Learn more" },
        { age: "Grades 1-5", title: "Primary Stage", description: "We build a strong foundation in reading, writing, and expression with an engaging approach that makes children love learning.", link: "Learn more" },
        { age: "Grades 6-9", title: "Middle Stage", description: "We develop analytical thinking and deep understanding skills, focusing on Arabic and Islamic Education in the UAE curriculum.", link: "Learn more" },
        { age: "Grades 10-12", title: "Secondary Stage", description: "We elevate students' mastery of Arabic and Islamic Education with intensive follow-up and comprehensive reviews.", link: "Learn more" },
      ],
      ctaBadge: "For Non-Arabic Speakers · All Ages",
      ctaTitle: "Arabic Language Course",
      ctaDesc: "We teach Arabic from scratch with an interactive and fun approach — reading, writing, and conversation, for any age without curriculum restrictions",
      ctaButton: "Register Now",
    },
    stats: {
      line1pre: "Experience over",
      line1num: "7",
      line1post: "years in teaching native and non-native Arabic speakers",
      line2num: "+200",
      line2post: "students",
      line3num: "+10",
      line3post: "specialized teachers",
    },
    paths: {
      title: "One philosophy &\ndifferent paths at every stage",
      items: [
        { age: "Grades 1-5", description: "Kids learn through play and hands-on experiments. With their teacher by their side, they try new things in a safe space where they feel comfortable asking questions.", tags: ["Short sessions", "Fun learning", "Developing curiosity"] },
        { age: "Grades 6-9", description: "Students begin building analytical thinking skills and working on real projects. We develop their problem-solving and logical thinking.", tags: ["Analytical thinking", "Real projects", "Continuous follow-up"] },
        { age: "Grades 10-12", description: "We elevate students' Arabic and Islamic Education with intensive reviews and customized study plans that suit their level and goals.", tags: ["Advanced skills", "Custom plan", "Intensive reviews"] },
      ],
      link: "Discover packages →",
    },
    trial: {
      heading1: "Start with a",
      headingHighlight: "free trial lesson",
      heading2: "and see how we work",
      steps: [
        { title: "Meet your teacher", description: "The session starts by getting to know your child — what they enjoy, what inspires them, and how they like to learn. Many children feel shy at first, so we focus on building trust and creating a calm, supportive atmosphere." },
        { title: "Discover the right path", description: "We recommend the best learning plan based on your child's level, age, and needs. We choose the most suitable subjects and teacher for them." },
        { title: "Get clear recommendations", description: "The teacher shares honest feedback: your child's level, the best starting point, and what they need to focus on. We design the learning path based on their interests and goals." },
      ],
      stepLabel: "Step",
      cta: "Try Now",
    },
    premiumHero: {
      title: "Majd Packages.. Because They Deserve Excellence",
      desc1: "Invest in your children's comfort and success with packages designed to support and understand them.",
      desc2: "A complete UAE curriculum with follow-up that makes them love studying, so they reach",
      desc2highlight: "excellence",
      desc3: "while feeling comfortable and happy.",
      cta: "Discover Our Packages",
    },
    packages: {
      subtitle: "Complete UAE curriculum from Grade 1 to 12",
      title: "Choose the right package",
      titleHighlight: "for your kids",
      cta: "Book Your Free Class",
      items: [
        { title: "Comprehensive Package", description: "Both subjects at a better price", price: "1600", period: "AED / month", features: ["Arabic + Islamic Education", "10 sessions/month with specialized teachers", "Continuous parent follow-up via WhatsApp", "Review sessions before exams"] },
        { title: "Basic Package", description: "One subject with continuous follow-up for Arabs", price: "1000", period: "AED / month", features: ["One subject (Arabic or Islamic Ed.)", "6 sessions/month with a specialized teacher", "Free trial session", "Monthly report for parents"] },
      ],
    },
    guarantees: {
      title: "Majd's Promise to Your Family",
      description: "Your trust is our responsibility. We guarantee a comfortable learning experience and always strive to provide the best.",
      cardTitle: "Our Guarantees",
      items: ["Replacement teacher if needed", "Make-up session for absences", "Guaranteed quality", "7-day support", "Safe & respectful environment"],
      cta: "Book a Free Class",
    },
    faq: {
      title: "FAQ",
      subtitle: "Answers to the most common questions from parents",
      items: [
        { question: "Can we change the teacher or schedule?", answer: "Absolutely! Your child's comfort is our priority. Contact us via WhatsApp or email and we'll arrange the change quickly at no extra cost." },
        { question: "Do classes work on phones or tablets?", answer: "Yes! Classes work on any device — laptop, tablet, or phone. We recommend a laptop or tablet for the best experience." },
        { question: "How can I track my child's progress?", answer: "We send regular reports via WhatsApp after each session, and a comprehensive monthly report with the teacher's assessment and recommendations." },
        { question: "Is there a free trial class?", answer: "Yes! We offer a free trial class so you can see the teaching quality and our approach before committing to any package." },
        { question: "How can I verify you're trustworthy?", answer: "We're officially registered and have been working for over 3 years with hundreds of families in the UAE. You can check parent reviews or contact us directly." },
      ],
      ctaText: "Didn't find your answer? Contact us",
    },
    testimonials: {
      subtitle: "Parent Reviews",
      title: "Their trust",
      titleHighlight: "motivates us",
      cta: "Join the Majd Family",
      items: [
        { name: "Abdullah's Mom", grade: "Grade 4", subject: "Arabic", text: "Abdullah used to hate Arabic class, but after starting with Majd he now asks to attend the session himself. The teacher's approach is amazing." },
        { name: "Shamma's Mom", grade: "Grade 7", subject: "Islamic Education", text: "Shamma struggled with memorization, but the teacher helped her understand the meaning first. Her grades went from 70 to 95." },
        { name: "Rashid's Mom", grade: "Grade 10", subject: "Arabic", text: "Rashid scored 98 in the final Arabic exam. The teacher followed up with him daily and reviewed everything. I honestly didn't expect this result." },
        { name: "Hamdan's Dad", grade: "Grade 2", subject: "Arabic", text: "Hamdan is 7 years old and now reads on his own. The sessions are short, focused, and he never gets bored. Best decision we made." },
        { name: "Maryam's Mom", grade: "Grade 9", subject: "Islamic Education", text: "Maryam used to fear exams. The teacher built her confidence and now she enters exams feeling relaxed. She got full marks in the second term." },
      ],
    },
    footer: {
      cta: "Free Lesson",
      col1Title: "Academy",
      col1Links: ["About Majd", "Our Method", "Teachers", "Teach with Us", "FAQ", "Contact Us"],
      col2Title: "Subjects",
      col2Links: ["Arabic Language", "Islamic Education", "Arabic for Non-Speakers"],
      col3Title: "Contact Us",
      col3Desc: "Stay updated with our latest offers and educational news",
      col3Placeholder: "Email address",
      col3Button: "Subscribe",
      col3Address: "Majd Academy for E-Learning\nUnited Arab Emirates",
      copyright: "© Majd, 2026",
      privacy: "Privacy Policy",
      terms: "Terms of Use",
    },
    whyMajd: {
      title1: "Why ",
      title2: "Majd?",
      footer: "Track your child's progress and what's coming up ahead, get feedback and review on every class.",
      features: [
        { title: "UAE Accredited Curriculum", desc: "We teach the Ministry of Education approved curriculum — the same as school but with a better approach." },
        { title: "Live Online Classes", desc: "1:1 sessions with specialized instructors who follow your child step by step." },
        { title: "Expert Subject Teachers", desc: "Our team is trained and specialized in the UAE curriculum and knows how to deliver." },
        { title: "Continuous Parent Follow-up", desc: "Regular reports and direct communication so you always know your child's progress." },
      ]
    },
    subjectsSection: {
      title1: "Subjects ",
      title2: "we teach",
      items: [
        { name: "Arabic Language", desc: "We build reading, writing, and expression skills in an engaging way that makes students love the language.", cta: "Book a free class" },
        { name: "Islamic Education", desc: "We instill Islamic values and concepts in a relatable way that connects faith to the student's daily life.", cta: "Book a free class" },
      ]
    }
  },
};

export type LandingContent = typeof landingContent.ar;
