export const landingContent = {
  ar: {
    hero: {
      line1: "مستقبل عيالك",
      line2: "يبدأ بخطوة ثابتة مع مَجْد",
      subtitle1: "دروس أونلاين بالمنهج الإماراتي مع معلمين متخصصين يحتوون عيالكم ويوصلونهم للتفوق.",
      subtitle2: "",
      cta: "احجز حصة مجانية",
      badge1: "المنهج الإماراتي",
      badge1sub: "وزارة التربية والتعليم",
      badge2: "EmSAT",
      badge2sub: "تحضير اختبارات الإمسات",
      badge3: "الصف 1 - 12",
      badge3sub: "جميع المراحل",
    },
    interests: {
      heading: "من الأول للثاني عشر، عيالك بأيدٍ",
      headingHighlight: "أمينة",
      cards: [
        { age: "الصف 1-5", title: "المرحلة الابتدائية", description: "نبني أساس قوي في القراءة والكتابة والحساب بأسلوب ممتع يحبب الطفل بالتعلم من البداية.", link: "اعرف أكثر" },
        { age: "الصف 6-9", title: "المرحلة المتوسطة", description: "نطوّر مهارات التفكير التحليلي والفهم العميق مع التركيز على المواد الأساسية بالمنهج الإماراتي.", link: "اعرف أكثر" },
        { age: "الصف 10-12", title: "المرحلة الثانوية", description: "نجهّز الطالب للامتحانات النهائية والإمسات بمتابعة مكثفة ومراجعات شاملة.", link: "اعرف أكثر" },
      ],
      ctaBadge: "لغير الناطقين بالعربية · جميع الأعمار",
      ctaTitle: "كورس اللغة العربية",
      ctaDesc: "نعلّم العربية من الصفر بأسلوب تفاعلي ممتع — قراءة وكتابة ومحادثة، لأي عمر وبدون ارتباط بمنهج محدد",
      ctaButton: "سجّل الآن",
    },
    stats: {
      line1pre: "أكثر من",
      line1num: "3",
      line1post: "سنوات تعليم ناجح",
      line2num: "+200",
      line2post: "طالب",
      line3num: "+10",
      line3post: "معلم متخصص",
    },
    paths: {
      title: "فلسفة واحدة ومسارات\nمختلفة لكل مرحلة",
      items: [
        { age: "الصف 1-5", description: "الأطفال يتعلمون من خلال اللعب والتجارب العملية. مع معلمهم بجانبهم، يجربون أشياء جديدة في مساحة آمنة يشعرون فيها بالراحة لطرح الأسئلة.", tags: ["حصص قصيرة", "تعلّم ممتع", "تنمية الفضول"] },
        { age: "الصف 6-9", description: "الطلاب يبدأون ببناء مهارات التفكير التحليلي والعمل على مشاريع حقيقية. نطوّر عندهم حل المشكلات والتفكير المنطقي.", tags: ["تفكير تحليلي", "مشاريع حقيقية", "متابعة مستمرة"] },
        { age: "الصف 10-12", description: "نجهّز الطالب للامتحانات النهائية والإمسات بمراجعات مكثفة وخطط دراسية مخصصة تناسب مستواه وأهدافه.", tags: ["تحضير الإمسات", "خطة مخصصة", "مراجعات مكثفة"] },
      ],
      link: "اكتشف الباقات ←",
    },
    trial: {
      heading1: "ابدأ بـ",
      headingHighlight: "حصة تجريبية مجانية",
      heading2: "وشوف كيف نشتغل",
      steps: [
        { title: "تعرّف على المعلم", description: "الحصة تبدأ بالتعرف على ولدك — شو يحب، شو يلهمه، وكيف يحب يتعلم. كثير من الأطفال يحسون بالخجل أول مرة، عشان جي نركز على بناء الثقة وخلق جو هادئ وداعم." },
        { title: "اكتشف المسار المناسب", description: "نوصي بأفضل خطة تعليمية بناءً على مستوى ولدك وعمره واحتياجاته. نختار المواد والمعلم الأنسب له." },
        { title: "احصل على توصيات واضحة", description: "المعلم يشارك ملاحظاته بصراحة: مستوى ولدك، أفضل نقطة بداية، وشو يحتاج يركز عليه. نصمم خطة التعلم حسب اهتماماته وأهدافه." },
      ],
      stepLabel: "الخطوة",
      cta: "جرّب الآن",
    },
    premiumHero: {
      title: "باقات مَجْد.. لأنهم يستاهلون التميز",
      desc1: "استثمر في راحة وتفوق عيالك مع باقات صممناها عشان تحتويهم وتفهم طريقتهم.",
      desc2: "منهج إماراتي متكامل بمتابعة تحببهم في الدراسة، عشان يوصلون",
      desc2highlight: "للمَجْد",
      desc3: "وهم مرتاحين ومستمتعين.",
      cta: "اكتشف باقاتنا",
    },
    packages: {
      subtitle: "منهج إماراتي متكامل من الصف الأول للثاني عشر",
      title: "اختار الباقة المناسبة",
      titleHighlight: "لعيالك",
      cta: "احجز حصتك المجانية",
      items: [
        { title: "الباقة الشاملة", description: "المادتين معاً بسعر أفضل", price: "600", period: "درهم / شهرياً", features: ["اللغة العربية + التربية الإسلامية", "8 حصص شهرياً مع معلمين متخصصين", "متابعة مستمرة لولي الأمر عبر الواتساب", "حصص مراجعة قبل الامتحانات"] },
        { title: "الباقة الأساسية", description: "مادة واحدة بمتابعة مستمرة", price: "400", period: "درهم / شهرياً", features: ["مادة واحدة (عربي أو تربية إسلامية)", "4 حصص شهرياً مع معلم متخصص", "حصة تجريبية لتقييم مستوى الطالب", "تقرير شهري لولي الأمر"] },
      ],
    },
    guarantees: {
      title: "وعد مَجْد لعيالكم",
      description: "ثقتكم فينا أمانة. نضمن لكم تجربة تعليمية مريحة — ولو ما عجبتكم الخدمة، نرجع لكم فلوسكم بدون أي سؤال.",
      cardTitle: "ضماناتنا لكم",
      items: ["استرداد خلال 7 أيام", "معلم بديل لو ما ناسب", "حصة تعويضية عند الغياب", "جودة مضمونة", "دعم مستمر 7 أيام", "بيئة آمنة ومحترمة"],
      cta: "احجز حصة مجانية",
    },
    faq: {
      title: "الأسئلة الشائعة",
      subtitle: "إجابات لأكثر الأسئلة اللي توصلنا من أولياء الأمور",
      items: [
        { question: "هل نقدر نغيّر المعلم أو الجدول؟", answer: "أكيد! أولويتنا راحة الطالب. تقدر تتواصل معنا عبر الواتساب أو الإيميل وبنرتب لك التغيير بأسرع وقت بدون أي تكلفة إضافية." },
        { question: "هل الحصص تشتغل على الجوال أو التابلت؟", answer: "نعم! الحصص تشتغل على أي جهاز — لابتوب، تابلت، أو جوال. بس ننصح باللابتوب أو التابلت عشان تجربة أفضل." },
        { question: "كيف أتابع مستوى ولدي؟", answer: "نرسل لك تقارير دورية عبر الواتساب بعد كل حصة، وتقرير شامل نهاية كل شهر فيه تقييم المعلم وتوصياته." },
        { question: "هل فيه حصة تجريبية مجانية؟", answer: "نعم! نوفر حصة تجريبية مجانية عشان تشوف بنفسك جودة التدريس وأسلوبنا قبل ما تلتزم بأي باقة." },
        { question: "كيف أتأكد إنكم موثوقين؟", answer: "نحن مسجلين رسمياً ونشتغل من أكثر من 3 سنوات مع مئات العائلات في الإمارات. تقدر تشوف آراء أولياء الأمور أو تتواصل معنا مباشرة." },
      ],
      ctaText: "ما لقيت جوابك؟ كلمنا",
    },
    testimonials: {
      subtitle: "آراء أولياء الأمور",
      title: "ثقتهم فينا",
      titleHighlight: "تحفّزنا",
      cta: "انضم لعائلة مَجْد",
      items: [
        { name: "أم عبدالله", grade: "الصف الرابع", subject: "اللغة العربية", text: "عبدالله كان يكره حصة العربي، بس بعد ما بدأ مع مَجْد صار يطلب مني يحضر الحصة بنفسه. المعلمة أسلوبها يجنن." },
        { name: "أم شمّا", grade: "الصف السابع", subject: "التربية الإسلامية", text: "شمّا كانت تعاني مع الحفظ، بس المعلمة خلتها تفهم المعنى أول وبعدين تحفظ. درجاتها ارتفعت من 70 لـ 95." },
        { name: "أم راشد", grade: "الصف العاشر", subject: "اللغة العربية", text: "راشد جاب 98 في امتحان العربي النهائي. المعلم كان يتابع معاه يومياً ويراجع كل شي. صراحة ما توقعت هالنتيجة." },
        { name: "أبو حمدان", grade: "الصف الثاني", subject: "اللغة العربية", text: "حمدان عمره 7 سنين وصار يقرأ لحاله. الحصص قصيرة ومركزة وما يمل منها. أحسن قرار أخذناه." },
        { name: "أم مريم", grade: "الصف التاسع", subject: "التربية الإسلامية", text: "مريم كانت تخاف من الامتحانات. المعلمة بنت عندها ثقة وصارت تدخل الامتحان مرتاحة. جابت فل مارك الترم الثاني." },
      ],
    },
    footer: {
      cta: "حصة مجانية",
      col1Title: "الأكاديمية",
      col1Links: ["عن مَجْد", "طريقتنا", "المعلمين", "انضم كمعلم", "الأسئلة الشائعة", "تواصل معنا"],
      col2Title: "المواد",
      col2Links: ["اللغة العربية", "التربية الإسلامية", "عربي لغير الناطقين"],
      col3Title: "تواصل معنا",
      col3Desc: "تابع آخر العروض والأخبار التعليمية",
      col3Placeholder: "البريد الإلكتروني",
      col3Button: "اشترك",
      col3Address: "أكاديمية مَجْد للتعليم الإلكتروني\nالإمارات العربية المتحدة",
      copyright: "© مَجْد، 2026",
      privacy: "سياسة الخصوصية",
      terms: "شروط الاستخدام",
    },
    whyMajd: {
      title1: "ليش ",
      title2: "مَجد؟",
      footer: "تابع تقدّم ولدك وشوف إيش الجاي، واحصل على ملاحظات المعلم بعد كل حصة.",
      features: [
        { title: "منهج إماراتي معتمد", desc: "ندرّس بالمنهج المعتمد من وزارة التربية والتعليم — نفس اللي يدرسونه في المدرسة بس بأسلوب أحلى." },
        { title: "حصص أونلاين تفاعلية", desc: "حصص فردية مع معلمين متخصصين يتابعون ولدك خطوة بخطوة." },
        { title: "معلمين خبراء بالمادة", desc: "فريقنا مدرّب ومتخصص بالمنهج الإماراتي ويعرف كيف يوصّل المعلومة." },
        { title: "متابعة مستمرة لولي الأمر", desc: "تقارير دورية وتواصل مباشر عشان دايماً تعرف وين وصل مستوى ولدك." },
      ]
    },
    subjectsSection: {
      title1: "المواد ",
      title2: "اللي ندرّسها",
      items: [
        { name: "اللغة العربية", desc: "نبني مهارات القراءة والكتابة والتعبير بأسلوب ممتع يحبب الطالب باللغة ويقوّي ثقته.", cta: "احجز حصة مجانية" },
        { name: "التربية الإسلامية", desc: "نغرس القيم والمفاهيم الإسلامية بطريقة قريبة من الطالب تربط الدين بحياته اليومية.", cta: "احجز حصة مجانية" },
      ]
    }
  },
  en: {
    hero: {
      line1: "Your kids' future",
      line2: "starts with a solid step with Majd",
      subtitle1: "Online classes following the UAE curriculum with specialized teachers who nurture your children and guide them to excel.",
      subtitle2: "",
      cta: "Book a Free Class",
      badge1: "UAE Curriculum",
      badge1sub: "Ministry of Education",
      badge2: "EmSAT",
      badge2sub: "EmSAT Exam Preparation",
      badge3: "Grades 1 - 12",
      badge3sub: "All Levels",
    },
    interests: {
      heading: "From Grade 1 to 12, your kids are in",
      headingHighlight: "safe hands",
      cards: [
        { age: "Grades 1-5", title: "Primary Stage", description: "We build a strong foundation in reading, writing, and math with an engaging approach that makes children love learning.", link: "Learn more" },
        { age: "Grades 6-9", title: "Middle Stage", description: "We develop analytical thinking and deep understanding skills, focusing on core subjects in the UAE curriculum.", link: "Learn more" },
        { age: "Grades 10-12", title: "Secondary Stage", description: "We prepare students for final exams and EmSAT with intensive follow-up and comprehensive reviews.", link: "Learn more" },
      ],
      ctaBadge: "For Non-Arabic Speakers · All Ages",
      ctaTitle: "Arabic Language Course",
      ctaDesc: "We teach Arabic from scratch with an interactive and fun approach — reading, writing, and conversation, for any age without curriculum restrictions",
      ctaButton: "Register Now",
    },
    stats: {
      line1pre: "Over",
      line1num: "3",
      line1post: "years of successful teaching",
      line2num: "+200",
      line2post: "students",
      line3num: "+10",
      line3post: "specialized teachers",
    },
    paths: {
      title: "One philosophy &\ndifferent paths at every stage",
      items: [
        { age: "Grades 1-5", description: "Kids learn through play and hands-on experiments. With their teacher by their side, they try new things in a safe space where they feel comfortable asking questions.", tags: ["Short sessions", "Fun learning", "Developing curiosity"] },
        { age: "Grades 6-9", description: "Students begin building analytical thinking skills and working on real projects. We develop their problem-solving and logical thinking.", tags: ["Analytical thinking", "Real projects", "Continuous follow-up"] },
        { age: "Grades 10-12", description: "We prepare students for final exams and EmSAT with intensive reviews and customized study plans that suit their level and goals.", tags: ["EmSAT prep", "Custom plan", "Intensive reviews"] },
      ],
      link: "Discover packages →",
    },
    trial: {
      heading1: "Start with a",
      headingHighlight: "free trial lesson",
      heading2: "and see how we work",
      steps: [
        { title: "Meet your teacher", description: "The session starts by getting to know your child — what they enjoy, what inspires them, and how they like to learn. Many children feel shy at first, so we focus on building trust and creating a calm, supportive atmosphere." },
        { title: "Discover the right path", description: "We recommend the best learning plan based on your child's level, age, and needs. We choose the most suitable subjects and teacher for them." },
        { title: "Get clear recommendations", description: "The teacher shares honest feedback: your child's level, the best starting point, and what they need to focus on. We design the learning path based on their interests and goals." },
      ],
      stepLabel: "Step",
      cta: "Try Now",
    },
    premiumHero: {
      title: "Majd Packages.. Because They Deserve Excellence",
      desc1: "Invest in your children's comfort and success with packages designed to support and understand them.",
      desc2: "A complete UAE curriculum with follow-up that makes them love studying, so they reach",
      desc2highlight: "excellence",
      desc3: "while feeling comfortable and happy.",
      cta: "Discover Our Packages",
    },
    packages: {
      subtitle: "Complete UAE curriculum from Grade 1 to 12",
      title: "Choose the right package",
      titleHighlight: "for your kids",
      cta: "Book Your Free Class",
      items: [
        { title: "Comprehensive Package", description: "Both subjects at a better price", price: "600", period: "AED / month", features: ["Arabic + Islamic Education", "8 sessions/month with specialized teachers", "Continuous parent follow-up via WhatsApp", "Review sessions before exams"] },
        { title: "Basic Package", description: "One subject with continuous follow-up", price: "400", period: "AED / month", features: ["One subject (Arabic or Islamic Ed.)", "4 sessions/month with a specialized teacher", "Free trial session to assess level", "Monthly report for parents"] },
      ],
    },
    guarantees: {
      title: "Majd's Promise to Your Family",
      description: "Your trust is our responsibility. We guarantee a comfortable learning experience — and if you're not satisfied, we'll refund you with no questions asked.",
      cardTitle: "Our Guarantees",
      items: ["7-day refund", "Replacement teacher if needed", "Make-up session for absences", "Guaranteed quality", "7-day support", "Safe & respectful environment"],
      cta: "Book a Free Class",
    },
    faq: {
      title: "FAQ",
      subtitle: "Answers to the most common questions from parents",
      items: [
        { question: "Can we change the teacher or schedule?", answer: "Absolutely! Your child's comfort is our priority. Contact us via WhatsApp or email and we'll arrange the change quickly at no extra cost." },
        { question: "Do classes work on phones or tablets?", answer: "Yes! Classes work on any device — laptop, tablet, or phone. We recommend a laptop or tablet for the best experience." },
        { question: "How can I track my child's progress?", answer: "We send regular reports via WhatsApp after each session, and a comprehensive monthly report with the teacher's assessment and recommendations." },
        { question: "Is there a free trial class?", answer: "Yes! We offer a free trial class so you can see the teaching quality and our approach before committing to any package." },
        { question: "How can I verify you're trustworthy?", answer: "We're officially registered and have been working for over 3 years with hundreds of families in the UAE. You can check parent reviews or contact us directly." },
      ],
      ctaText: "Didn't find your answer? Contact us",
    },
    testimonials: {
      subtitle: "Parent Reviews",
      title: "Their trust",
      titleHighlight: "motivates us",
      cta: "Join the Majd Family",
      items: [
        { name: "Abdullah's Mom", grade: "Grade 4", subject: "Arabic", text: "Abdullah used to hate Arabic class, but after starting with Majd he now asks to attend the session himself. The teacher's approach is amazing." },
        { name: "Shamma's Mom", grade: "Grade 7", subject: "Islamic Education", text: "Shamma struggled with memorization, but the teacher helped her understand the meaning first. Her grades went from 70 to 95." },
        { name: "Rashid's Mom", grade: "Grade 10", subject: "Arabic", text: "Rashid scored 98 in the final Arabic exam. The teacher followed up with him daily and reviewed everything. I honestly didn't expect this result." },
        { name: "Hamdan's Dad", grade: "Grade 2", subject: "Arabic", text: "Hamdan is 7 years old and now reads on his own. The sessions are short, focused, and he never gets bored. Best decision we made." },
        { name: "Maryam's Mom", grade: "Grade 9", subject: "Islamic Education", text: "Maryam used to fear exams. The teacher built her confidence and now she enters exams feeling relaxed. She got full marks in the second term." },
      ],
    },
    footer: {
      cta: "Free Lesson",
      col1Title: "Academy",
      col1Links: ["About Majd", "Our Method", "Teachers", "Teach with Us", "FAQ", "Contact Us"],
      col2Title: "Subjects",
      col2Links: ["Arabic Language", "Islamic Education", "Arabic for Non-Speakers"],
      col3Title: "Contact Us",
      col3Desc: "Stay updated with our latest offers and educational news",
      col3Placeholder: "Email address",
      col3Button: "Subscribe",
      col3Address: "Majd Academy for E-Learning\nUnited Arab Emirates",
      copyright: "© Majd, 2026",
      privacy: "Privacy Policy",
      terms: "Terms of Use",
    },
    whyMajd: {
      title1: "Why ",
      title2: "Majd?",
      footer: "Track your child's progress and what's coming up ahead, get feedback and review on every class.",
      features: [
        { title: "UAE Accredited Curriculum", desc: "We teach the Ministry of Education approved curriculum — the same as school but with a better approach." },
        { title: "Live Online Classes", desc: "1:1 sessions with specialized instructors who follow your child step by step." },
        { title: "Expert Subject Teachers", desc: "Our team is trained and specialized in the UAE curriculum and knows how to deliver." },
        { title: "Continuous Parent Follow-up", desc: "Regular reports and direct communication so you always know your child's progress." },
      ]
    },
    subjectsSection: {
      title1: "Subjects ",
      title2: "we teach",
      items: [
        { name: "Arabic Language", desc: "We build reading, writing, and expression skills in an engaging way that makes students love the language.", cta: "Book a free class" },
        { name: "Islamic Education", desc: "We instill Islamic values and concepts in a relatable way that connects faith to the student's daily life.", cta: "Book a free class" },
      ]
    }
  },
};

export type LandingContent = typeof landingContent.ar;
